### PR TITLE
Add UnsupportedRtcpFbPacket type.

### PR DESCRIPTION
**Pull request by JonathanLennox**

### CODE REVIEW

**Comment by bbaldino** [comment]
Do you think we need a new type here instead of just using `UnsupportedRtcpPacket`?

**Comment by JonathanLennox** [comment]
> Do you think we need a new type here instead of just using `UnsupportedRtcpPacket`?

I guess not.  We might want to add a string or something to `UnsupportedRtcpPacket` that gives more detail about what was unsupported?

**Comment by bbaldino** [comment]
> > Do you think we need a new type here instead of just using `UnsupportedRtcpPacket`?
> 
> I guess not. We might want to add a string or something to `UnsupportedRtcpPacket` that gives more detail about what was unsupported?

Sure, that'd be nice to have but I don't see it as too urgent.

**Comment by JonathanLennox** [comment]
Actually, the reason we need it is that `RtcpFbPacket.parse` returns `RtcpFbPacket`, so unless we want to change that, we need to return a subtype of `RtcpFbPacket`.

**Comment by bbaldino** [comment]
> Actually, the reason we need it is that `RtcpFbPacket.parse` returns `RtcpFbPacket`, so unless we want to change that, we need to return a subtype of `RtcpFbPacket`.

Ah, good point.

**Pull request merged**
