### PR TITLE
ktlint: Do NOT use --apply-to-idea-project

### PR DESCRIPTION
**Pull request by bgrozev**
because it silently overrides the *Java* code style settings. Do not
run in the mvn validate phase. Use pre-commit hook instead of pre-push.

### CODE REVIEW

**Comment by bgrozev** [comment]
Don't merge yet, WIP

**Comment by bbaldino** [comment]
Shit, good catch. Didn't know this overrides the Java settings (no idea why
it would do that...)

**Comment by bgrozev** [comment]
Yeah, it doesn't seem right. I asked upstream
https://github.com/pinterest/ktlint/issues/378

**Comment by bbaldino** [comment]
Ok cool. Btw I looked at it after seeing this and there is a dedicated
maven plugin by someone (https://github.com/gantsign/ktlint-maven-plugin)--i
totally missed that before I guesss.  but didn't look at it deeper.

**Comment by bgrozev** [comment]
We can move to the mvn plugin later.

I removed running it as part of the maven workflow, because I use `mvn install` with 'dirty' code all the time.

Personally I prefer a pre-commit hook, otherwise if I only notice when I'm trying to push I might need to rebase to fix earlier commits. But I wouldn't mind having both. I think there must be a way to have them installed automatically on checkout, but I couldn't find out how with a quick seach.

Same applies to the jmt commit PR that I'll open tomorrow

**Comment by bgrozev** [comment]
No I left a note in the readme and was going to leave it for later

**Pull request merged**
