### PR TITLE
Adds a payload verification string to Packet.

### PR DESCRIPTION
**Pull request by bgrozev**

### CODE REVIEW

**Comment by bgrozev** [comment]
It's more of a permanent debug thing. The intention is to use it to make sure that new code we introduce doesn't modify the payload (it can be automated, too). By default it is disabled so the expensive hashCode method is never called, but the way it works is:
1. There's a switch to enable/disable it via HTTP
2. PacketInfo stores the expected verification strings
3. Node verifies that transform() did not change the payload
4. Code which intentionally modifies the payload reset's the expected value

I guess if we're already running the check and printing warning, we might as well include the payload. The easy way would be significantly more expensive (passing around a long string in PacketInfo, comparing it every time), but it could definitely be useful when we do break something. Let me think about it, I'll probably change it

**Comment by bbaldino** [comment]
My thought was that if this is already expensive, then maybe the payload isn't all that much worse since we won't be doing it at any significant scale anyway.  Also, to me this seems like the sort of thing that would be more useful in a test environment (like the pcap harnesses) and not really necessary in production...it seems like the sort of bug that either happens or doesn't, so reproducing it wouldn't be hard and therefore not all that necessary to be able to turn it on (though I certainly don't mind that as a feature--I'm just not sure how much we'd use it for this sort of thing?)

Also, I was thinking we could make the payload has stuff extensions functions defined in JMT, rather than having to modify RTP as the methods don't access anything that isn't available publicly, and this debug mechanism is more of a JMT-level thing anyway? Not strictly necessary, but would keep all the logic for this in one place (JMT).

**Comment by bgrozev** [comment]
> My thought was that if this is already expensive, then maybe the payload isn't all that much worse since we won't be doing it at any significant scale anyway.

Agreed, I'll include that.

> Also, to me this seems like the sort of thing that would be more useful in a test environment (like the pcap harnesses) and not really necessary in production...it seems like the sort of bug that either happens or doesn't, so reproducing it wouldn't be hard and therefore not all that necessary to be able to turn it on (though I certainly don't mind that as a feature--I'm just not sure how much we'd use it for this sort of thing?)

I agree half-way. Having it in the testing harness would be nice, but it is much more useful to have it for live code. The bug could only be reproducible in certain scenarios that our unit test cases don't test for. 
Example: The header extension bug that would only manifest with Octo.
Example: We are currently seeing some video artefacts that are hard to reproduce. Running this on a live meeting (NOT in production, obviously) would allow us to either find what messed up the payload, or be reasonably sure that the payload itself is not the problem.

Further, having this enabled for the functional tests would be even better, because it would catch things that happen only with ceretain browsers, or when browser versions are updated. It would be quite simple and I have it on my list (will add a card to keep track of it) to have the PR testing scripts enable payload verification and fail the test if after all the tests any payload was changed (along with other analysis of the info exposed in /colibri/stats).


> Also, I was thinking we could make the payload hash stuff extensions functions defined in JMT, rather than having to modify RTP as the methods don't access anything that isn't available publicly

I'll see if I can make that work. I'm not sure that inheritance will work the way I want it (e.g. if I have a `val rtpPacket: RtpPacket` which is actually a `Vp8VideoPacket`, would `rtpPacket.payloadVerification` correctly access the function defined for `Vp8VideoPacket`). I'll try.

**Comment by bgrozev** [comment]
I kept `payloadVerification` in `Packet` because of the lack of inheritance when using extension functions. I added all of the payload though.

**Pull request merged**
