### PR TITLE
ktlint 0.34.2 cleanups.

### PR DESCRIPTION
**Pull request by JonathanLennox**
(Mostly "Imports must be ordered in lexicographic order without any
empty lines in-between" and "File must end with a newline".)

### CODE REVIEW

**Comment by bbaldino** [comment]
oh, did you mean to update the pom as well? (the ktlint version)

**Comment by JonathanLennox** [comment]
I didn't update the ktlint verrsion in the pom, because unfortunately they don't seem to have released a version to Maven since 0.31.0 in March.

**Comment by bbaldino** [comment]
hm, i think maybe it's moved to be under the pinterest org now: https://mvnrepository.com/artifact/com.pinterest.ktlint

**Comment by JonathanLennox** [comment]
Oh, right, yes.  You want this in this PR, or a separate one?

**Comment by bbaldino** [comment]
let's do it in this one alongside the changes themselves.

**Pull request merged**
